CREATE TABLE [dbo].[Customer]
(
  [Id] UNIQUEIDENTIFIER  DEFAULT(newid()) NOT NULL PRIMARY KEY,
  [UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[Users]([Id]) ON DELETE CASCADE UNIQUE,
  [CustomerId] NVARCHAR(255) NOT NULL,
  [Email] NVARCHAR(255) NOT NULL UNIQUE,
  [Created] DATETIMEOFFSET NOT NULL,
  [Updated] DATETIMEOFFSET NULL,
)
