CREATE TABLE [dbo].[Guest]
(
  [Id] UNIQUEIDENTIFIER DEFAULT(newid()) NOT NULL PRIMARY KEY,
  [IpAddress] NVARCHAR(255) NOT NULL,
  [Links] INT NOT NULL DEFAULT(0),
  [Blocked] BIT NOT NULL DEFAULT(0),
  [BlockedUntil] DATETIMEOFFSET NULL,
  [Created] DATETIMEOFFSET NOT NULL,
  [Updated] DATETIMEOFFSET NULL,
)
