CREATE TABLE [dbo].[Links]
(
  [Id] UNIQUEIDENTIFIER DEFAULT(newid()) NOT NULL PRIMARY KEY,
  [UserId] UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES [dbo].[Users]([Id]) ON DELETE CASCADE UNIQUE,
  [GuestId] UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES [dbo].[Guest]([Id]) ON DELETE CASCADE UNIQUE,
  [Custom] BIT NOT NULL DEFAULT(0),
  [Code] NVARCHAR(255) NOT NULL,
  [Url] NVARCHAR(255) NOT NULL,
  [OriginalUrl] NVARCHAR(255) NOT NULL,
  [Active] BIT NOT NULL DEFAULT(1),
  [Created] DATETIMEOFFSET NOT NULL,
  [Updated] DATETIMEOFFSET NULL,
)
