CREATE TABLE [dbo].[LinkStats]
(
  [Id] UNIQUEIDENTIFIER DEFAULT(newid()) NOT NULL PRIMARY KEY,
  [LinkId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[Links]([Id]) ON DELETE CASCADE,
  [Visits] INT NOT NULL DEFAULT(0),
  [Browser] NVARCHAR(MAX) NULL,
  [Device] NVARCHAR(MAX) NULL,
  [Platform] NVARCHAR(MAX) NULL,
  [Country] NVARCHAR(MAX) NULL,
  [Created] DATETIMEOFFSET NOT NULL,
  [Updated] DATETIMEOFFSET NULL,
)
