CREATE TABLE [dbo].[RefreshTokens]
(
  [Id] UNIQUEIDENTIFIER DEFAULT(newid()) NOT NULL PRIMARY KEY,
  [Token] NVARCHAR(MAX) NOT NULL,
  [UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [Users](Id) ON DELETE CASCADE,
  [Active] BIT NOT NULL DEFAULT(1),
  [Expires] DATETIMEOFFSET NOT NULL,
  [Created] DATETIMEOFFSET NOT NULL,
  [Updated] DATETIMEOFFSET NULL,
)
