CREATE TABLE [dbo].[Session]
(
  [Id] UNIQUEIDENTIFIER DEFAULT(newid()) NOT NULL PRIMARY KEY,
  [UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [Users](Id) ON DELETE CASCADE,
  [Expires] DATETIMEOFFSET NOT NULL,
  [Created] DATETIMEOFFSET NOT NULL,
  [Updated] DATETIMEOFFSET NULL,
)
