CREATE TABLE [dbo].[Subscriptions]
(
  [Id] UNIQUEIDENTIFIER DEFAULT(newid()) NOT NULL PRIMARY KEY,
  [SubscriptionId] NVARCHAR(255) NOT NULL,
  [UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[Users]([Id]) ON DELETE CASCADE UNIQUE,
  [Expires] DATETIMEOFFSET NOT NULL,
  [Created] DATETIMEOFFSET NOT NULL,
  [Updated] DATETIMEOFFSET NULL,
)
