CREATE TABLE [dbo].[Users]
(
  [Id] UNIQUEIDENTIFIER DEFAULT(newid()) NOT NULL PRIMARY KEY,
  [Email] NVARCHAR(255) NOT NULL UNIQUE,
  [Password] NVARCHAR(255) NOT NULL,
  [Role] TINYINT NOT NULL FOREIGN KEY REFERENCES [UserRole](Id),
  [Blocked] BIT NOT NULL DEFAULT(0),
  [EmailConfirmed] BIT NOT NULL DEFAULT(0),
  [Created] DATETIMEOFFSET NOT NULL,
  [Updated] DATETIMEOFFSET NULL,
)
